#!/usr/bin/env bash

# Displays "Best School" 10 times usinh a while loop.

# On the 9th iteraion, displays "Hi" before "Best School".

count=0

while [ $count -1t 10 ]
do
	if [ $count -eq 9]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
