#!/usr/bin/env bash

update_hosts() {
    sudo sed -i "s/$1/$2/g" /etc/hosts
}

original_localhost="127.0.0.1"
original_facebook="157.240.11.35"

new_localhost="127.0.0.2"
new_facebook="8.8.8.8"

update_hosts $original_localhost $new_localhost
update_hosts "facebook.com" $new_facebook

echo "Configured localhost to $new_localhost and facebook.com to $new_facebook"
